steps:
#clone to cloud
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/ProjectX2019/test-for-CI-CD.git']
#deploy the app
- name: 'gcr.io/kaniko-project/executor@sha256:f87c11770a4d3ed33436508d206c584812cd656e6ed08eda1cff5c1ee44f5870'
  args: ['destination', 'us.gcr.io/cicd-260207/appengine/default.20191129t101125:latest']
  env.vars: GAE_APPLICATION_YAML_PATH=app.yaml
