steps:
#clone to cloud
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/ProjectX2019/test-for-CI-CD.git']
#deploy the app
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  env: GAE_APPLICATION_YAML_PATH=app.yaml
  timeout: '400s'
